DjangoWebProject2/urls.py
"""
Definition of urls for DjangoWebProject2.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^pool$', app.views.pool, name='pool'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Вход',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog


class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class PoolForm(forms.Form):
    name = forms.CharField(label = 'Ваше имя', min_length=2, max_length=100)
    city = forms.CharField(label = 'Ваш город', min_length=2, max_length=100)    
    mark = forms.ChoiceField(label = 'Оцените качество услуг', choices=[('1', 'Плохое'), ('2', 'Среднее'), ('3', 'Хорошее')], widget=forms.RadioSelect, initial=1)
    message = forms.CharField(label = 'Ваше впечатление от использования сервиса', widget=forms.Textarea(attrs={'rows':12, 'cols':40}))


class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text


class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog # используемая модель
        fields = ('title', 'description', 'content', 'image',) # заполняемые поля
        labels = {'title': "Заголовок", 'description': "Краткое содержание", 'content': "Полное содержание", 'image': "Картинка"} # метки к полям

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}
<h2>{{ title }}</h2> <br />

{% for post in posts %}
<hr/>
<div class="">
    <h2> {{post.title}} </h2>
    <h4> {{post.posted}} </h4>
    <p> {{post.description}} </p>    
    <p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
    <p style="color:gray"> {{post.author}} </p>    
</div>
{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
    <img src="{{ post_1.image.url }}" alt="Картинка" width="300"/>
{% endif %}
<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам#}
<p class="author">     Опубликовано: {{post_1.author}} {{post_1.posted}}</p>
<p><a href="{% url 'blog' %}"> Назад </a> </p>

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST" >{% csrf_token %} {# защита от атак CSRF#}
        <div>
            {{form.as_p}}
            <button type="submit" class="save btn btn-default" > Отправить комментарий </button>
        </div>
    </form>
{% else %}
    <h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %}

{% for comment in comments %}
    <hr/>
    <h7> {{comment.date}} </h7>
    <h5> {{comment.author}} </h5>
    <p> {{comment.text|linebreaksbr}} </p>
{% endfor %}

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Фирма<br />
    Улица, дом<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Техническая поддрежка:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Отдел маркетинга:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Мой сайт Веб 2.0</h1>
    <p class="lead">В будущем очень полезный сайт.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Поехали</h2>
        <p>
            Куча крутого и пафосного текста про Веб 2.0
            Куча крутого и пафосного текста про сайт.
            Куча крутого и пафосного текста про что-нибудь.
        </p>
        <p><a class="btn btn-default" href="http://www.djangobook.com/en/2.0/index.html">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Дополнительно</h2>
        <p>Что-то про Питон.</p>
        <p><a class="btn btn-default" href="https://pypi.org/">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Реклама</h2>
        <p>Облака Майкрософт самые белые и пушистые на сегодняшний день.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/20130405234230179.png' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    {% if user.is_superuser %}
                        <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                    <li><a href="{% url 'pool' %}">Обратная связь</a></li>
                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>
    
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

    {% load staticfiles %}

<a href ="https://lukoshko.net/" target="_blank"><img src="{% static 'app/content/logo_autumn.png' %}" alt="Logo 1"/></a>

{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Вход для зарегистрированных пользователей.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста введител верные имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Вход</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}


    <h3>Добавить статью</h3>
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %} {# обязательная защита от атак CSRF #}
        <div>
            {{ blogform.as_p }}
            <button type="submit" class="save btn btn-default" > Сохранить статью </button>
        </div>
    </form>

{% endblock %}

app/templates/app/pool.html
{% extends "app/layout.html" %}
{% block content %}
{% if form != None %}
    <br><h2>Оставьте пожалуйста отзыв о качестве предоставленных услуг</h2><br>
    <div>
        <form method="post">
            {% csrf_token %}
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name }}<br><br>
            <label for="{{ form.city.id_for_label }}">{{ form.city.label }}</label>
            {{ form.city }}<br><br>
            <label for="{{ form.mark.id_for_label }}">{{ form.mark.label }}</label>
            {{ form.mark }}<br>
            <div><label for="{{ form.message.id_for_label }}">{{ form.message.label }}</label></div>
            <div>{{ form.message }}</div><br><br>
            <input id="b1" type="submit" value="Отправить">
            <script>
                function b1_over()
                {
                    $('#b1').css('background-color', 'yellow')
                }

                function b1_out()
                {
                    $('#b1').css('background-color', 'WhiteSmoke')
                }

                function field_name_focus()
                {
                    $('#id_name').css('background-color', 'silver')
                }

                 function field_name_blur()
                {
                    $('#id_name').css('background-color', 'white')
                }

                function field_city_focus()
                {
                    $('#id_city').css('background-color', 'silver')
                }

                 function field_city_blur()
                {
                    $('#id_city').css('background-color', 'white')
                }

                $('#b1').mouseover(b1_over);
                $('#b1').mouseout(b1_out);
                $('#id_name').focus(field_name_focus);
                $('#id_name').blur(field_name_blur);
                $('#id_city').focus(field_city_focus);
                $('#id_city').blur(field_city_blur);
            </script>
        </form>
    </div>
{% else %}
    <br><h2>Боагодарим за вашу оценку!</h2>
    <h3>Вы отправили на портал следующую информацию:</h3>
    <ul>
        <li><span>Имя:</span> {{ data.name }}</li>
        <li><span>Город:</span> {{ data.city }}</li>
        <li><span>Оценка сервиса:</span> {{ data.mark }}</li>
        <li><span>Мнение о сервисе:</span> {{ data.message }}</li>
    </ul>
{% endif %}
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
    <h2>Регистрация пользователя</h2>
    <form method="POST" > {% csrf_token %}
        <div>
            {{ regform.as_p}}
            <button type="submit" class="save btn btn-default" > Зарегистрировать </button>
        </div>
    </form>
{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>

<div>
    <h1>Видео-ролик 1</h1>
    <VIDEO src="/media/5.mp4" controls="controls" width="400" height="300" poster="/media/5.jpg" ></VIDEO>
</div>

{% endblock %}